# Generated by Django 5.1.5 on 2025-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_type', models.CharField(max_length=30)),
                ('ice_cream_name', models.CharField(max_length=30)),
                ('ice_cream_quantity', models.PositiveIntegerField()),
                ('ice_cream_weight', models.PositiveIntegerField(verbose_name='weight in Grams')),
                ('Registered_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
