# Generated by Django 5.1.5 on 2025-01-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='Registered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_quantity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ice_Cream.icecreamname'),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ice_Cream.icecreamtype'),
        ),
    ]
