# Generated by Django 5.1.5 on 2025-01-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0002_icecreamname_icecreamtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecreaminfo',
            old_name='Registered_date',
            new_name='registered_date',
        ),
    ]
