# Generated by Django 5.1.5 on 2025-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0005_alter_icecreaminfo_ice_cream_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreaminfo',
            name='registered_date',
            field=models.DateField(auto_now=True),
        ),
    ]
