# Generated by Django 5.1.5 on 2025-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0006_alter_icecreaminfo_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_name',
            field=models.CharField(choices=[('MCH', 'Madagascar choco'), ('FVN', 'French Vanilla'), ('SBF', 'Strawberry fudge'), ('CRD', 'caramel dip'), ('FOR', 'Fresh Orange')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_weight',
            field=models.CharField(choices=[('100', '100gms'), ('250', '250gms'), ('500', '500gms')], default=None, max_length=6, null=True),
        ),
    ]
