# Generated by Django 5.1.5 on 2025-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0007_alter_icecreaminfo_ice_cream_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_weight',
            field=models.CharField(choices=[('100gms', '100gms'), ('250gms', '250gms'), ('500gms', '500gms')], default=None, max_length=6, null=True),
        ),
    ]
