# Generated by Django 5.1.5 on 2025-01-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0008_alter_icecreaminfo_ice_cream_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecreaminfo',
            name='ice_cream_quantity',
        ),
    ]
