# Generated by Django 5.1.5 on 2025-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0010_alter_icecreaminfo_ice_cream_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_flavour',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_name',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_weight',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
