# Generated by Django 5.1.5 on 2025-01-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ice_Cream', '0013_alter_icecreaminfo_ice_cream_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreaminfo',
            name='ice_cream_flavour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ice_Cream.icecreamflavor'),
        ),
    ]
