# Generated by Django 5.1.4 on 2025-01-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
