# Generated by Django 5.1.4 on 2025-01-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_exam_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='sub5',
            field=models.PositiveIntegerField(verbose_name='Science'),
        ),
    ]
