# Generated by Django 5.1.4 on 2025-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_examtype_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
    ]
