# Generated by Django 5.1.4 on 2025-01-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_failedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedstudent',
            name='exam',
        ),
        migrations.AddField(
            model_name='failedstudent',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.examtype'),
        ),
    ]
