# Generated by Django 5.1.4 on 2025-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_remove_failedstudent_exam_failedstudent_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedstudent',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
