# Generated by Django 5.1.4 on 2025-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_remove_failedstudent_status_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
