# Generated by Django 5.1.4 on 2025-01-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0012_alter_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.AddField(
            model_name='failedstudent',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
