# Generated by Django 5.1.4 on 2025-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0014_alter_failedstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedstudent',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
