# Generated by Django 4.2 on 2025-01-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0016_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomwisesubjectwithteacher',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroomwisesubjectwithteacher',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.teacher'),
        ),
    ]
