# Generated by Django 4.2 on 2025-01-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0017_classroomwisesubjectwithteacher_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomwisesubjectwithteacher',
            name='subject',
        ),
    ]
