# Generated by Django 4.2 on 2025-01-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0019_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sub7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.subject'),
        ),
    ]
