# Generated by Django 4.2 on 2025-01-13 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0021_sports_alter_exam_sub7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.sports')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.exam')),
            ],
        ),
    ]
