# Generated by Django 4.2 on 2025-01-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0022_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='sub7',
        ),
    ]
