# Generated by Django 4.2 on 2025-01-13 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0023_remove_exam_sub7'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWithHobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='student',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='total',
        ),
        migrations.AddField(
            model_name='exam',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.hobbies'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobby',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
        migrations.AddField(
            model_name='studentwithhobbies',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.hobbies'),
        ),
        migrations.AddField(
            model_name='studentwithhobbies',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentwithhobbies',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.exam'),
        ),
    ]
