# Generated by Django 4.2 on 2025-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0024_studentwithhobbies_remove_hobbies_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='hobby',
        ),
        migrations.AddField(
            model_name='exam',
            name='hobby',
            field=models.ManyToManyField(null=True, to='studentapp.hobbies'),
        ),
    ]
