# Generated by Django 4.2 on 2025-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0025_remove_exam_hobby_exam_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='hobby',
            field=models.ManyToManyField(to='studentapp.hobbies'),
        ),
    ]
